version: 1
settings:
  one-use: false
  # Makes the command one use only
  require-perm: false
  # Makes the command require a permission
  max-dist: 5000
  # Max distance away from specified location. 5000 = -5000 to 5000 in x and z
  min-dist: 100
  # Min distance away from the center of the RTP teleport range
  pointx: 0
  pointz: 0
  # The center of the RTP teleport range. X and Z coords
  wait-time: 3
  # Time to wait before teleportation. Useful if chunks aren't loading fast enough. Time is in seconds
  world-dest: world
  # The specified world to teleport to
  cooldown: 60
  # Amount of seconds to wait before player can use the command again
messages:
  run-rtp: Beginning RTP.
  # Message to send when RTP command is ran
  after-rtp:
  # Message to send after RTP command is ran
  no-perm: You don't have permission to run this command.
  # Message to send when lacking permission to run RTP command
  used-once: You've already used this command once
  # Message to send when command has already been used
  invalid-player: Invalid player specified
  # Message to send when an invalid player is specified for a command