name: YetAnotherRTP
version: '${project.version}'
main: com.github.bitbyte.yetanotherrtp.YetAnotherRTP
api-version: 1.19
author: 1BitByte
commands:
  rtp:
    description: Main RTP command
  addused:
    description: Allows someone to reuse the RTP command
    permission: rtp.add
  removeused:
    description: Makes the plugin act as if they've already used the RTP command
    permission: rtp.remove
permissions:
  rtp.runcmd:
    default: op
  rtp.exempt:
    description: Exempts players from the cooldown time